import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const distDir = resolve(projectRoot, 'dist');

const collectFiles = async directory => {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(entries.map(async entry => {
    const path = resolve(directory, entry.name);
    return entry.isDirectory() ? collectFiles(path) : [path];
  }));
  return nested.flat();
};

const files = (await collectFiles(distDir))
  .filter(path => !['sw.js', 'version.json'].includes(relative(distDir, path)))
  .sort();
const hash = createHash('sha256');
for (const file of files) {
  hash.update(relative(distDir, file));
  hash.update(await readFile(file));
}
const version = hash.digest('hex').slice(0, 12);
const precacheUrls = ['./', ...files.map(file => `./${relative(distDir, file).split(sep).join('/')}`)];
const optionalExternalUrls = [
  'https://cdn.tailwindcss.com/',
  'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,500;9..144,600&display=swap',
];

const serviceWorker = `/* PiPlate release ${version}. Generated by scripts/build-pwa.mjs. */
const RELEASE = ${JSON.stringify(version)};
const PRECACHE = \`piplate-precache-\${RELEASE}\`;
const RUNTIME = \`piplate-runtime-\${RELEASE}\`;
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};
const OPTIONAL_EXTERNAL_URLS = ${JSON.stringify(optionalExternalUrls, null, 2)};

self.addEventListener('install', event => {
  event.waitUntil(caches.open(PRECACHE).then(async cache => {
    await cache.addAll(PRECACHE_URLS);
    await Promise.allSettled(OPTIONAL_EXTERNAL_URLS.map(async url => {
      const request = new Request(url, { mode: 'no-cors' });
      const response = await fetch(request);
      await cache.put(request, response);
    }));
  }));
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(key => key.startsWith('piplate-') && ![PRECACHE, RUNTIME].includes(key)).map(key => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('message', event => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

const cacheResponse = async (request, response) => {
  if (response.ok || response.type === 'opaque') {
    const cache = await caches.open(RUNTIME);
    await cache.put(request, response.clone());
  }
  return response;
};

self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;

  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request)
        .then(response => cacheResponse(event.request, response))
        .catch(async () => (await caches.match(event.request)) || caches.match('./index.html'))
    );
    return;
  }

  event.respondWith(
    caches.match(event.request).then(cached => cached || fetch(event.request).then(response => cacheResponse(event.request, response)))
  );
});
`;

await writeFile(resolve(distDir, 'sw.js'), serviceWorker);
await writeFile(resolve(distDir, 'version.json'), `${JSON.stringify({ version })}\n`);
console.log(`PiPlate PWA release ${version}: ${precacheUrls.length} files cached for offline use.`);
